name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: |
          yarn --frozen-lockfile
      - run: |
          yarn cdk deploy \
            -c googleClientId=${{ secrets.GOOGLE_CLIENT_ID }} \
            -c googleClientSecret=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -c feedbackEmail=${{ secrets.FEEDBACK_EMAIL }} \
            -c domainName=${{ secrets.DOMAIN_NAME }} \
            --require-approval never \
            --all
