name: deploy
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
env:
  AWS_REGION: ap-northeast-1
  DOMAIN_NAME: chiptube.io
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - run: |
          yarn --frozen-lockfile
      - run: |
          yarn cdk deploy \
            -c googleClientId=${{ secrets.GOOGLE_CLIENT_ID }} \
            -c googleClientSecret=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -c googleSearchConsoleVerificationCode=${{ secrets.GOOGLE_SEARCH_CONSOLE_VERIFICATION_CODE }} \
            -c adminEmail=${{ secrets.ADMIN_EMAIL }} \
            -c domainName=${{ env.DOMAIN_NAME }} \
            -c githubRepository=${{ github.repository }} \
            -c githubRef=${{ github.ref }} \
            --require-approval never \
            --all
